### PR TITLE
Patch dist barrier

### PR DESCRIPTION
**Pull request by GeorgiosSmyrnis**
Make sure that all processes exit at the same time (so that remote is synced properly).

### CODE REVIEW

**Comment by achalddave** [comment]
This looks good to me but did you get a chance to test @GeorgiosSmyrnis?

**Comment by GeorgiosSmyrnis** [comment]
Yes I did a run and it does not hang - I think that is sufficient for this.

**Comment by achalddave** [comment]
approved - go ahead and merge after tests pass!

**Comment by sagadre** [comment]
@GeorgiosSmyrnis version bump for downstream?

**Comment by GeorgiosSmyrnis** [comment]
@sagadre thanks for pointing it out - added one!

**Pull request merged**
