### PR TITLE
tests: run in GitHub Actions

### PR DESCRIPTION
**Pull request by iejMac**
cc: @achalddave

### CODE REVIEW

**Comment by iejMac** [comment]
what config did we run black with previously? I'm getting this:
Screenshot 2023-11-19 at 4 48 20 AM

**Comment by iejMac** [comment]
gtg now but seems we might have issues running some tests on actions - https://github.com/iejMac/open_lm/actions/runs/6920555691/job/18825172957

**Comment by iejMac** [comment]
idk maybe we add a flag in each test specifying if GPU is required for the test and this in combination with torch.cuda.is_available() determines if the test is run

**Comment by achalddave** [comment]
This is excellent, thank you @iejMac! 

> maybe we add a flag in each test specifying if GPU is required
That's a great idea. Another implementation is we can add a marker (e.g. pytest.marker.slow like https://github.com/mlfoundations/open_lm/pull/74/files#diff-c6de978711d26a475be05d36d51cc1c1e097c35cc6cfaef47c83d553c0a533cbR73) and just skip those in the Github action.

I think this is a reasonable short term fix while we also figure out how to get a GPU for testing. I'll look into this this week.

Re: black - my guess is someone forgot to run black, or their code ran it with the wrong config. Could you run black in this commit with the right config and get that test to pass?

**Comment by iejMac** [comment]
@achalddave Its ready to go. If you could:
- do a final review
- check https://github.com/iejMac/open_lm/actions/runs/6936947839/job/18870060633 to see that it all passes
then let me know if you think its good. After that I need to make one more commit changing so it runs on main and PRs to main only (right now its set to this branch so I can see tests)

**Comment by iejMac** [comment]
in the future tests that require GPUs should get marked the `@pytest.mark.gpu` marker and can be run via `make test-gpu`

**Comment by achalddave** [comment]
This looks great, thanks again!

**Review by achalddave — APPROVED** [review]

**Pull request merged**
