### PR TITLE
README update re: dataloader.

### PR DESCRIPTION
**Pull request by GeorgiosSmyrnis**
A more detailed description of the behavior of the dataloader without replacement.

### CODE REVIEW

**Comment by achalddave** [comment]
This looks good, but can we either:
(1) error if the requested number of checkpoints is higher than possible, with a warning that says what the user should do, or
(2) print a large warning message indicating that we are checkpointing less?

**Comment by GeorgiosSmyrnis** [comment]
I added a warning message if this is detected, and pointing out how to alleviate it. I'm not sure if this is something that should error necessarily.

**Comment by achalddave** [comment]
I assume this is out of date and we don't need this anymore right? @GeorgiosSmyrnis

**Comment by GeorgiosSmyrnis** [comment]
You're right @achalddave - closing this.

**Pull request closed without merging**
