### PR TITLE
Fix S3 streaming issues

### PR DESCRIPTION
**Pull request by rams16592**
File streaming used to fail without retries so trying to load the complete file before using it downline.
Tried this with Stack data and had issues so fixed it and now streaming issues are resolved.

### CODE REVIEW

**Comment by Vaishaal** [comment]
Can we make this a flag, I think this might cause memory usage to increase?

**Comment by rams16592** [comment]
@Vaishaal 
I have added a flag to enable BytesIO or BinaryIO and its defaulted to BinaryIO.

**Comment by Vaishaal** [comment]
Can you make this PR with main instead?

**Comment by rams16592** [comment]
@Vaishaal 
I have updated the PR to go to main

**Comment by rams16592** [comment]
Updating through a new PR: https://github.com/mlfoundations/open_lm/pull/174

**Pull request closed without merging**
